# run scripts with include [script_name]

# clean memory
reset;

model impianto.mod;
data impianto1.dat;

# solve and display results
option solver cplex;
solve;

# show results with display [var]
display x;
display Profitto;

# clean memory
reset;

model impianto.mod;
data impianto2.dat;

# solve and display results
option solver cplex;
solve;

# show results with display [var]
display x;
display Profitto;

